# Generated by Django 5.0.6 on 2024-07-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('Sage', models.IntegerField()),
                ('Semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
